### ISSUE TITLE
[BUG] Test TestScavengerWithCompressionMemoryCache.testAllExpired failed

### ISSUE THREAD

**Issue by VladRodionov** [carrotdata/carrot-cache#373]
```
java.lang.AssertionError: expected:<0> but was:<11752>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at com.carrotdata.cache.TestScavengerBase.testAllExpired(TestScavengerBase.java:163)
```

**Comment by VladRodionov** [comment]
No longer observed
